job_name: 'A3C for Pong'
env: 'PongDeterministic-v0'
agent: 'a3c'
learning_rate: 0.0001
discount: 0.99
t_max: 20
num_processes: 16
num_episodes_per_process: 1000
use_atari_wrapper: True
monitor_dir: ''
