job_name: 'A3C for Self-play MyPong'
env: 'Pong-2p-v0'
agent: 'a3c'
learning_rate: 0.0001
discount: 0.99
t_max: 20
num_processes: 16
num_episodes_per_process: 1000
init_model_path: ''
checkpoint_freq: 20
checkpoint_dir: 'checkpoints'
use_atari_wrapper: True
monitor_dir: ''
