- job_name: 'DQN for CartPole' 
  env: 'CartPole-v0' 
  agent: 'dqn'
  monitor_dir: ''
  num_episodes: 50
  batch_size: 128
  learning_rate: 0.001
  discount: 1.0
  random_explore: 0.05


- job_name: 'Random for CartPole' 
  env: 'CartPole-v0' 
  agent: 'random'
  monitor_dir: ''
  num_episodes: 50


- job_name: 'TabularQ for Roulette'
  env: 'Roulette-v0' 
  agent: 'tabular_q'
  monitor_dir: ''
  num_episodes: 50
  q_value_init: 0.0
  learning_rate: 0.1
  discount: 1.0
  random_explore: 0.1
